# [module]
# [module.hugoVersion]
# min = "0.109.0"
# extended = true
# 
# [[module.imports]]
# path = "github.com/juggernautjp/hugo-widebs5-theme"
# [[module.mounts]]
# source = "assets/scss"
# target = "assets/docs/scss"
# [[module.mounts]]
# source = "assets/js"
# target = "assets/docs/js"
# [[module.mounts]]
# source = "assets"
# target = "assets"
# [[module.mounts]]
# source = "content"
# target = "content"
# [[module.mounts]]
# source = "layout"
# target = "layout"
