# cite from Hugo Docs' config
description = "The world’s fastest framework for building websites"
## Setting this to true will add a "noindex" to *EVERY* page on the site..
removefromexternalsearch = false
## Gh repo for site footer (include trailing slash)
ghrepo = "https://github.com/gohugoio/hugoDocs/"
## GH Repo for filing a new issue
github_repo = "https://github.com/gohugoio/hugo/issues/new"
### Edit content repo (set to automatically enter "edit" mode; this is good for "improve this page" links)
ghdocsrepo = "https://github.com/gohugoio/hugoDocs/tree/master/docs"
## Gitter URL
gitter = "https://gitter.im/spf13/hugo"
## Discuss Forum URL
forum = "https://discourse.gohugo.io/"
## Google Tag Manager
gtmid = ""
## Search URL by Flexsearch
search_url = "/search"

# footer links
hugo_hp = "https://gohugo.io/"
bootstrap_hp = "https://getbootstrap.com/"
cloudflare_pages = "https://www.cloudflare.com/ja-jp/products/pages/"

# [View on GitHub] links
repo = "https://github.com/juggernautjp/gohugo-docs-ja"

# First one is picked as the Twitter card image if not set on page.
images = ["images/gohugoio-card.png"]

flex_box_interior_classes = "flex-auto w-100 w-40-l mr3 mb3 bg-white ba b--moon-gray nested-copy-line-height"

#sidebar_direction = "sidebar_left"


# The followings are .Site.Params for hugo-theme-zen:
# The Sass transpiler to use, default "libsass".
sassTranspiler = "dartsass"
# Max number of search hits, default 20.
searchLimit = 20

# The followings are .Site.Params for hugo-widebs5-theme:
# include for "Carbon Ads" (only Bootstrap site)
enableCarbonAds = false

# include for DocSearch (only Bootstrap site)
enableDocSearch = false

# include Docs Version dropdown menu (only Bootstrap site)
menuDocsVersion = false
