
  enableInlineShortcodes = false

  [exec]
    allow = ['^go$', '^npx$' ]
    osEnv = ['^PATH$']

  [funcs]
    getenv = ['^HUGO_', '^REPOSITORY_URL$', '^BRANCH$']

  [http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
