[[docs]]
  name = "About Hugo"
  weight = 10
  identifier = "about"
  url = "/en/about/"

[[docs]]
  name = "Installation"
  weight = 20
  identifier = "installation"
  url = "/en/installation/"

[[docs]]
  name = "Getting Started"
  weight = 30
  identifier = "getting-started"
  url = "/en/getting-started/"

[[docs]]
  name = "Hugo Modules"
  weight = 40
  identifier = "modules"
  post = "break"
  url = "/en/hugo-modules/"

# Core menus

[[docs]]
  name = "Content Management"
  weight = 50
  identifier = "content-management"
  post = "expanded"
  url = "/en/content-management/"

[[docs]]
  name = "Templates"
  weight = 60
  identifier = "templates"

  url = "/en/templates/"

[[docs]]
  name = "Functions"
  weight = 70
  identifier = "functions"
  url = "/en/functions/"

[[docs]]
  name = "Variables"
  weight = 80
  identifier = "variables"
  url = "/en/variables/"
[[docs]]
  name = "Hugo Pipes"
  weight = 90
  identifier = "pipes"
  url = "/en/hugo-pipes/"
[[docs]]
  name = "CLI"
  weight = 100
  post = "break"
  identifier = "commands"
  url = "/en/commands/"

# Low level items

[[docs]]
  name = "Troubleshooting"
  weight = 110
  identifier = "troubleshooting"
  url = "/en/troubleshooting/"

[[docs]]
  name = "Tools"
  weight = 120
  identifier = "tools"
  url = "/en/tools/"

[[docs]]
  name = "Hosting & Deployment"
  weight = 130
  identifier = "hosting-and-deployment"
  url = "/en/hosting-and-deployment/"

[[docs]]
  name = "Contribute"
  weight = 140
  post = "break"
  identifier = "contribute"
  url = "/en/contribute/"

######## QUICKLINKS

  [[quicklinks]]
    name = "Fundamentals"
    weight = 1
    identifier = "fundamentals"
    url = "/en/tags/fundamentals/"




######## GLOBAL ITEMS TO BE SHARED WITH THE HUGO SITES

[[global]]
    name = "News"
    weight = 1
    # identifier = "news"
    external = false
    icon = false
    url = "/en/news/"

  [[global]]
    name = "Docs"
    weight = 5
    # identifier = "docs"
    external = false
    icon = false
    url = "/en/documentation/"

[[global]]
  name = "Themes"
  weight = 10
  # identifier = "themes"
  external = true
  icon = false
  url = "https://themes.gohugo.io/"

    [[global]]
      name = "Showcase"
      weight = 20
      # identifier = "showcase"
      icon = false
      external = true
      url = "/en/showcase/"

# Anything with a weight > 100 gets an external icon

[[global]]
  name = "Community"
  weight = 150
  # identifier = "community"
  icon = true
  external = true
  url = "https://discourse.gohugo.io/"

[[global]]
  name = "GitHub"
  weight = 200
  identifier = "github"
  external = true
  url = "https://github.com/gohugoio/hugo"
